## Pre-commit setup
# See https://github.com/python-discord/code-jam-template/tree/main#pre-commit-run-linting-before-committing
#
# Please uncomment the right lines depending on your setup.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-docstring-first
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.2
    hooks:
      - id: isort
        args:
          [--trailing-comma]

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations~=2.0
          - flake8-isort~=4.0

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
        args: [--check-untyped-defs, --ignore-missing-imports]
